### ISSUE TITLE
Get a portion of map

### ISSUE THREAD

**Issue by Salvodif** [Ragath/TiledLib.Net#10]
Is there possible work with only a portion of the whole map?

**Comment by Ragath** [comment]
Well this library loads the entire map into memory. But there's nothing stopping you from only using a subset of this data when processing it further. The output of this library is designed to be an intermediate format that you then transfer over to something that's designed specifically for your usecase.

If its an optimization step where you want to skip part of the files(cutting out a section of layers) when parsing them, then its possible to do that on uncompressed files but not out of the box. You'd also have issues working with that format in Tiled, since its going to load the whole thing when editing.
